import { MinesBoardBlockState } from "./mines-board-block-state";

export const INITIAL_MINES_BOARD: MinesBoardBlockState[][] = [
  [
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
  ],
  [
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
  ],
  [
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
  ],
  [
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
  ],
  [
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
    MinesBoardBlockState.EMPTY,
  ],
];
